server:
  port: 5001
spring:
  application:
    name: lemon-ws-gateway
  data:
    redis:
      host: 124.223.178.180
      port: 16379
      password: g136T1NKClmsW77eLl
      database: 5
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.30.133:8848
        namespace: e5786474-e639-47fb-90a6-4696ef907e5a
        secret-key: QVNKQ0FTTERMQTpMOlNLQ01BTEtTTEtESkxBS0NNTkFTQk5ETkFCVjxBTlNKREhLSkFTQkRLSkFOU0Q=
        group: DEFAULT_GROUP
im:
  server:
    wsPath: /ws-server
    port: 9900
    print-banner: true
zookeeper:
  url: localhost:2181
  sessionTimeout: 2000
  root: /lemon_server_node